ruby '2.5.1'
source 'https://rubygems.org'
gem 'rails', '5.2.1'

gem 'active_decorator'
gem 'array_form_helper'
gem 'coffee-rails'
gem 'dotenv-rails'
gem 'doorkeeper', '>= 4.2.0'
gem 'kaminari'
gem 'exception_notification'
gem 'exception_notification-pushbullet'
gem 'the_garage'
gem 'garage-doorkeeper'
gem 'geocoder'
gem 'http'
gem 'holiday_jp'
gem 'icalendar'
gem 'jquery-rails'
gem 'json', '>= 2.0.0'
gem 'nokogiri', '>= 1.8.1'
gem 'rinku'
gem 'oauth2'
gem 'omniauth'
gem 'omniauth-facebook'
gem 'omniauth-twitter'
gem 'omniauth-google-oauth2'
gem 'pg'
gem 'rambulance'
gem 'rollbar'
gem 'sass-rails'
gem 'sprockets', '~> 3.7'
gem 'skylight'
gem 'puma'
gem 'slim-rails'
gem 'turbolinks', '~> 5.2.0'
gem 'uglifier', '>= 1.3.0'
gem 'pghero'
gem 'pg_query', '>= 0.9.0'

group :development do
  gem 'derailed_benchmarks'
  gem 'rack-mini-profiler'
  gem 'stackprof'
  gem 'web-console', '>= 2.1.3'
end

group :development, :test do
  gem 'brakeman'
  gem 'listen', '~> 3.1.5'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
  gem 'byebug'
end

group :test do
  gem 'activesupport-testing-metadata'
  gem 'capybara'
  gem 'coveralls', require: false
  gem 'launchy'
  gem 'minitest-sound'
  gem 'minitest-slow_test'
  gem 'minitest-test_profile'
  gem 'minitest-sub_test_case'
  gem 'vcr'
  gem 'webmock'
  gem 'selenium-webdriver'
  gem 'chromedriver-helper'
  gem 'screenshot_opener'
end
