ruby '2.4.1'

source 'https://rubygems.org'

gem 'active_decorator'
gem 'array_form_helper'
gem 'coffee-rails'
gem 'dotenv-rails'
gem 'doorkeeper', '>= 4.2.0'
gem 'kaminari'
gem 'exception_notification'
gem 'exception_notification-pushbullet'
gem 'the_garage'
gem 'garage-doorkeeper'
gem 'geocoder'
gem 'rails-footnotes'
gem 'http'
gem 'holiday_jp'
gem 'icalendar'
gem 'jquery-rails'
gem 'json', '>= 2.0.0'
gem 'nokogiri', '>= 1.6.8'
gem 'oauth2'
gem 'omniauth'
gem 'omniauth-facebook'
gem 'omniauth-twitter'
gem 'omniauth-google-oauth2'
gem 'picasa'
gem 'pg'
gem 'rails', '5.1.0'
gem 'rambulance'
gem 'ransack'
gem 'rollbar'
gem 'sass-rails'
gem 'sprockets', '~> 3.0'
gem 'skylight'
gem 'puma'
gem 'slim-rails'
gem 'turbolinks', '~> 5.0.0'
gem 'uglifier', '>= 1.3.0'

group :development do
  gem 'derailed_benchmarks'
  gem 'rack-mini-profiler'
  gem 'stackprof'
  gem 'web-console', '>= 2.1.3'
end

group :development, :test do
  gem 'brakeman'
  gem 'listen', '~> 3.0.5'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
  gem 'pry-rails'
  gem 'pry-nav'
end

group :test do
  gem 'activesupport-testing-metadata'
  gem 'capybara'
  gem 'coveralls', require: false
  gem 'launchy'
  gem 'minitest-sound'
  gem 'minitest-slow_test'
  gem 'minitest-test_profile'
  gem 'poltergeist'
  gem 'vcr'
  gem 'webmock'
end

